# Generated by Django 2.2.5 on 2019-11-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ativos',
        ),
    ]
